name = "openai-cf"                # todo
main = "index.js"
compatibility_date = "2022-05-03"

compatibility_flags = [
	"transformstream_enable_standard_constructor",
	"streams_enable_constructors",
]

[ai]
binding = "AI" # i.e. available in your Worker on env.AI

[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "openai-cf-images"
preview_bucket_name = "ai-images"

[vars]
CLOUDFLARE_ACCOUNT_ID = "c083c1643823ab3ca7351ef94cce2e6e" # replace with your own. 
