name: Deploy Cloudflare Worker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # 根据需要选择 Node.js 版本

      - name: Install dependencies
        run: yarn

      - name: Set Cloudflare Account ID
        run: |
          sed -i "s/c8c30db3dddc4ad31065d336368c7905/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/g" wrangler.toml

      - name: Deploy to Cloudflare
        run: |
          yarn init-prod
          yarn deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Set Secrets
        run: |
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV
        shell: bash

      - name: Configure Wrangler Secrets
        run: |
          wrangler secret put ACCESS_TOKEN --value $ACCESS_TOKEN
          wrangler secret put CLOUDFLARE_API_TOKEN --value $CLOUDFLARE_API_TOKEN
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
