name: Deploy cloudflare-workers-openai-mock

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Clone repository
        run: git clone https://github.com/pew/cloudflare-workers-openai-mock.git

      - name: Install dependencies
        run: npm install
        working-directory: ./cloudflare-workers-openai-mock

      - name: Install wrangler
        run: npm install -g wrangler
        working-directory: ./cloudflare-workers-openai-mock

      - name: Set Cloudflare Account ID
        run: |
          sed -i "s/true/false/g" wrangler.toml
        working-directory: ./cloudflare-workers-openai-mock

      - name: Deploy to Cloudflare Workers
        run: npm run deploy
        working-directory: ./cloudflare-workers-openai-mock
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Set Secrets with Wrangler
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | npx wrangler secret put token ACCESS_TOKEN
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        working-directory: ./cloudflare-workers-openai-mock
