name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 或者是您用于部署的任何分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Set Cloudflare Account ID
        run: |
          sed -i "s/c8c30db3dddc4ad31065d336368c7905/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/g" wrangler.toml

      - name: Initialize Production Environment
        run: |
          yarn init-prod || echo "Bucket already exists or another init error occurred, continuing with deployment..."

      - name: Deploy to Cloudflare
        run: |
          yarn deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Set Secrets with Wrangler
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | wrangler secret put ACCESS_TOKEN
          echo "${{ secrets.CLOUDFLARE_API_TOKEN }}" | wrangler secret put CLOUDFLARE_API_TOKEN
        shell: bash
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
