name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Deploy to Cloudflare
        run: |
          yarn init-prod
          yarn deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Set Secrets
        run: |
          wrangler secret put ACCESS_TOKEN --value ${{ secrets.ACCESS_TOKEN }}
          wrangler secret put CLOUDFLARE_API_TOKEN --value ${{ secrets.CLOUDFLARE_API_TOKEN }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
